### PR TITLE
backend: Repeat the info about available update if the client asks about it again for the same app

### LINKED ISSUE #76: Second update request unexpectedly returns updateInProgressOnInstance
When sending a first request to the update server the response is the new version as expected. However, subsequent requests show `error-updateInProgressOnInstance` which is not consistent with CoreOS' CoreUpdate.

### How to reproduce

Using this request file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.0" version="update_engine-0.4.10" updaterversion="update_engine-0.4.10" installsource="scheduler" ismachine="1">
    <os version="Chateau" platform="CoreOS" sp="2191.0.0_x86_64"></os>
    <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="2191.0.0" track="alpha" bootid="{90b0e235-2b50-4a0e-9619-bc014ca2fcfd}" oem="" oemversion="" alephversion="2191.0.0" machineid="592cfdb69c7f4a29a6b361b60cedd954" lang="en-US" board="amd64-usr" hardware_class="" delta_okay="false" >
        <ping active="1"></ping>
        <updatecheck></updatecheck>
        <event eventtype="3" eventresult="2" previousversion="0.0.0.0"></event>
    </app>
</request>
</xml>
</details>
```

#### Nebraska behavior

```console
core@flatcar-01 ~ $ curl -s -X POST -d @request.xml https://public.update.flatcar-linux.net/v1/update/ | xmllint --pretty 1 -
<?xml version="1.0"?>
<response protocol="3.0" server="coreroller">
  <daystart elapsed_seconds="0"/>
  <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="2191.0.0" status="ok" track="alpha">
    <ping status="ok"/>
    <updatecheck status="ok">
      <urls>
        <url codebase="https://update.release.flatcar-linux.net/amd64-usr/2275.0.0/"/>
      </urls>
      <manifest version="2275.0.0">
        <packages>
          <package hash="Xh+rt5I8pFTDVj1j+eKlt85JsKE=" name="flatcar_production_update.gz" size="466774008" required="true"/>
        </packages>
        <actions>
          <action event="postinstall" ChromeOSVersion="" sha256="mHsavz23FdX0uvlF1NHHcpJz2HU9qY33eoyC1Y6F+2Q=" needsadmin="false" IsDelta="false" DisablePayloadBackoff="true"/>
        </actions>
      </manifest>
    </updatecheck>
    <event status="ok"/>
  </app>
</response>
core@flatcar-01 ~ $ curl -s -X POST -d @request.xml https://public.update.flatcar-linux.net/v1/update/ | xmllint --pretty 1 -
<?xml version="1.0"?>
<response protocol="3.0" server="coreroller">
  <daystart elapsed_seconds="0"/>
  <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="2191.0.0" status="error-updateInProgressOnInstance" track="alpha">
    <ping status="ok"/>
    <event status="ok"/>
  </app>
</response>
```

#### CoreUpdate behavior

```console
core@flatcar-01 ~ $ curl -X POST -d @request.xml https://public.update.core-os.net/v1/update/
<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="ok">
   <urls>
    <url codebase="https://update.release.core-os.net/amd64-usr/2275.0.0/"></url>
   </urls>
   <manifest version="2275.0.0">
    <packages>
     <package name="update.gz" hash="2dePfsufko+c0o/OJOG2VHzf0OA=" hash_sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" size="467681292" required="false"></package>
    </packages>
    <actions>
     <action event="postinstall" sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" DisablePayloadBackoff="true"></action>
    </actions>
   </manifest>
  </updatecheck>
 </app>
</response>
core@flatcar-01 ~ $ curl -X POST -d @request.xml https://public.update.core-os.net/v1/update/
<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="ok">
   <urls>
    <url codebase="https://update.release.core-os.net/amd64-usr/2275.0.0/"></url>
   </urls>
   <manifest version="2275.0.0">
    <packages>
     <package name="update.gz" hash="2dePfsufko+c0o/OJOG2VHzf0OA=" hash_sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" size="467681292" required="false"></package>
    </packages>
    <actions>
     <action event="postinstall" sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" DisablePayloadBackoff="true"></action>
    </actions>
   </manifest>
  </updatecheck>
 </app>
</response>
```

### PR DESCRIPTION
**Pull request by krnowak**
Here is my "knee-jerk reaction" fix for #76. All the existing tests seem to pass, but probably some other test is needed, but for that I would like to know what behaviour is actually desired. There is obviously a problem that there is no explanation what this temporary hack was supposed to work around, which leaves me wondering what kind of workflow this change is going to break…

Fixes #76.

### CODE REVIEW

**Comment by joaquimrocha** [comment]
(I'll try to discuss this directly on Slack so we move faster)

**Comment by krnowak** [comment]
The changes in database with the "temporary hack" removed were mostly about updating the status of the instance (from granted update to complete), but I'm not really sure what should we expect here.

I went with a different fix now - we special case the "update granted" state, so instead of returning the "update in progress" error, we return the information about the package update again. This causes no database changes.

File: pkg/api/updates_test.go [hunk 1]
```diff
@@ -250,9 +250,15 @@ func TestGetUpdatePackage_UpdateInProgressOnInstance(t *testing.T) {
...
-	_, err := a.GetUpdatePackage(instanceID, "10.0.0.1", "12.0.0", tApp.ID, tGroup.ID)
+	p1, err := a.GetUpdatePackage(instanceID, "10.0.0.1", "12.0.0", tApp.ID, tGroup.ID)
+	assert.NoError(t, err)
+
+	p2, err := a.GetUpdatePackage(instanceID, "10.0.0.1", "12.0.0", tApp.ID, tGroup.ID)
 	assert.NoError(t, err)
+	assert.Equal(t, p1, p2)
 
+	err = a.updateInstanceStatus(instanceID, tApp.ID, InstanceStatusDownloading)
+	assert.NoError(t, err)
```
Comment (joaquimrocha) [inline pkg/api/updates_test.go]: Thanks for the tests!
